FROM trafex/php-nginx:3.11.1

USER root

RUN apk add --no-cache \
    git \
    unzip \
    ffmpeg \
    mediainfo \
    postgresql-client \
    php85-zip \
    php85-pgsql \
    php85-pdo_pgsql \
    php85-simplexml \
    php85-xmlwriter \
    php85-xmlreader \
    php85-fileinfo

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN mkdir -p /var/www/.composer /var/www/html/vendor \
    && chown -R nobody:nobody /var/www

USER nobody
