-- Ensure scan_status.id uses a generated identity and the sequence is aligned
DO $$
BEGIN
    -- Only convert if the column is not already an identity
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'scan_status'
          AND column_name = 'id'
          AND is_identity = 'YES'
    ) THEN
        -- Drop legacy default/sequence from BIGSERIAL
        EXECUTE 'ALTER TABLE public.scan_status ALTER COLUMN id DROP DEFAULT';

        -- Drop the old sequence if present
        IF EXISTS (
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind = 'S'
              AND n.nspname = 'public'
              AND c.relname = split_part(pg_get_serial_sequence('public.scan_status','id'), '.', 2)
        ) THEN
            EXECUTE 'DROP SEQUENCE IF EXISTS ' || pg_get_serial_sequence('public.scan_status','id') || ' CASCADE';
        END IF;

        -- Add identity
        EXECUTE 'ALTER TABLE public.scan_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
    END IF;
END$$;

-- Align sequence/identity with existing max id
SELECT setval(
    pg_get_serial_sequence('public.scan_status', 'id'),
    COALESCE((SELECT MAX(id) FROM public.scan_status), 0) + 1,
    false
);
